import { TrackerState } from '../models/token-models';

export const initialTrackerState: TrackerState = {
  tokens: [
    {
      tokenName: 'BTCUSDT',
      price: 0,
      dailyChange: 0,
      global: true,
      displayGlobalFullName: 'BTC',
      displayGlobalShortName: 'Bitcoin',
    },
    {
      tokenName: 'ETHUSDT',
      price: 0,
      dailyChange: 0,
      global: true,
      displayGlobalShortName: 'ETH',
      displayGlobalFullName: 'Ethereum',
    },
    {
      tokenName: 'SOLUSDT',
      price: 0,
      dailyChange: 0,
      global: false,
      displayGlobalShortName: 'SOL',
      displayGlobalFullName: 'Solana',
    },
    {
      tokenName: 'ETCUSDT',
      price: 0,
      dailyChange: 0,
      global: false,
    },
    {
      tokenName: 'BNBUSDT',
      price: 0,
      dailyChange: 0,
      global: true,
      displayGlobalShortName: 'BNB',
      displayGlobalFullName: 'Binance Coin',
    },
    {
      tokenName: 'ADAUSDT',
      price: 0,
      dailyChange: 0,
      global: false,
    },
    {
      tokenName: 'MATICUSDT',
      price: 0,
      dailyChange: 0,
      global: false,
    },
    {
      tokenName: 'XRPUSDT',
      price: 0,
      dailyChange: 0,
      global: false,
      displayGlobalShortName: 'XRP',
      displayGlobalFullName: 'Ripple',
    },
    {
      tokenName: 'AVAXUSDT',
      price: 0,
      dailyChange: 0,
      global: true,
      displayGlobalShortName: 'AVAX',
      displayGlobalFullName: 'Avalanche',
    },
    {
      tokenName: 'DOGEUSDT',
      price: 0,
      dailyChange: 0,
      global: false,
    },
    {
      tokenName: 'LTCUSDT',
      price: 0,
      dailyChange: 0,
      global: false,
      displayGlobalShortName: 'LTC',
      displayGlobalFullName: 'Litecoin',
    },
    {
      tokenName: 'DOTUSDT',
      price: 0,
      dailyChange: 0,
      global: true,
      displayGlobalShortName: 'DOT',
      displayGlobalFullName: 'Polkadot',
    },
    {
      tokenName: 'SHIBUSDT',
      price: 0,
      dailyChange: 0,
      global: false,
    },
    {
      tokenName: 'TRXUSDT',
      price: 0,
      dailyChange: 0,
      global: false,
    },
    {
      tokenName: 'LINKUSDT',
      price: 0,
      dailyChange: 0,
      global: false,
    },
    {
      tokenName: 'NEARUSDT',
      price: 0,
      dailyChange: 0,
      global: false,
    },
    {
      tokenName: 'CAKEUSDT',
      price: 0,
      dailyChange: 0,
      global: false,
      displayGlobalShortName: 'CAKE',
      displayGlobalFullName: 'PancakeSwap',
    },
    {
      tokenName: 'SUSHIUSDT',
      price: 0,
      dailyChange: 0,
      global: false,
      displayGlobalShortName: 'SUSHI',
      displayGlobalFullName: 'Sushi',
    },
    {
      tokenName: 'UNIUSDT',
      price: 0,
      dailyChange: 0,
      global: false,
      displayGlobalShortName: 'UNI',
      displayGlobalFullName: 'Uniswap',
    },
    {
      tokenName: 'AAVEUSDT',
      price: 0,
      dailyChange: 0,
      global: false,
    },
    {
      tokenName: 'ATOMUSDT',
      price: 0,
      dailyChange: 0,
      global: false,
    },
    {
      tokenName: 'GMTUSDT',
      price: 0,
      dailyChange: 0,
      global: false,
    },
    {
      tokenName: 'RUNEUSDT',
      price: 0,
      dailyChange: 0,
      global: false,
    },
    {
      tokenName: 'TWTUSDT',
      price: 0,
      dailyChange: 0,
      global: false,
      displayGlobalShortName: 'TWT',
      displayGlobalFullName: 'Trust Wallet Token',
    },
    {
      tokenName: 'ZECUSDT',
      price: 0,
      dailyChange: 0,
      global: false,
    },
    {
      tokenName: '1INCHUSDT',
      price: 0,
      dailyChange: 0,
      global: false,
    },
    {
      tokenName: 'LUNAUSDT',
      price: 0,
      dailyChange: 0,
      global: false,
    },
    {
      tokenName: 'MANAUSDT',
      price: 0,
      dailyChange: 0,
      global: false,
    },
    {
      tokenName: 'GLMRUSDT',
      price: 0,
      dailyChange: 0,
      global: false,
    },
  ],

  logs: [
    {
      id: Math.random().toFixed(8),
      tokenName: 'TWTUSDT',
      buyPrice: 0.75,
      sellPrice: null,
      quantity: 125,
      ratioGainLoss: 0,
      status: 'active',
    },
    {
      id: Math.random().toFixed(8),
      tokenName: 'BTCUSDT',
      buyPrice: 13500,
      sellPrice: null,
      quantity: 0.655,
      ratioGainLoss: 0,
      status: 'active',
    },
    {
      id: Math.random().toFixed(8),
      tokenName: 'AVAXUSDT',
      buyPrice: 19,
      sellPrice: 24,
      quantity: 50,
      ratioGainLoss: 0,
      status: 'sold',
    },
    {
      id: Math.random().toFixed(8),
      tokenName: 'SUSHIUSDT',
      buyPrice: 1.225,
      sellPrice: 1.552,
      quantity: 800,
      ratioGainLoss: 0,
      status: 'sold',
    },
  ],
};
